### ISSUE TITLE
problem related to webrtc

### ISSUE THREAD

**Issue by liujingbbd** [StanfordSNR/pantheon#25]
can not run webrtc.py successfully, and the problem as follow: 

![1](https://user-images.githubusercontent.com/16717748/34664983-90a3343e-f499-11e7-8cf1-ccf4e6b23704.png)

![2](https://user-images.githubusercontent.com/16717748/34664979-8a1908e6-f499-11e7-9376-7861113e279c.png)

I guess it may be caused by chromium-browser, but I don't know how to repair it.

**Comment by francisyyan** [comment]
Did you install all the dependencies required by WebRTC (`./webrtc.py deps`)? Then make sure you could run `chromium-browser` in the terminal.

If still not working, you could comment out the two lines `os.environ['DISPLAY'] = ':1'` and `os.environ['DISPLAY'] = ':2'` in `webrtc.py` and see if there are two browser windows popping up and playing the same video.

Otherwise, you might have to run all the commands (in `Popen`, `check_call`, `check_output`, `call`, etc.) in `webrtc.py` manually in the terminal. For example, you need to run the signaling server (`node app.js <port>`) on the sender side before running the sender. Then run the receiver in another terminal.

Besides, if you have more questions, please send them to our mailing list for archiving purposes: `pantheon-stanford <at> googlegroups <dot> com`. I will close this for now as it seems not to be an issue in our code, but please feel free to send us emails! Thanks!
