### ISSUE TITLE
Wrappers of Taova and Copa break when cc_repo path contains spaces

### ISSUE THREAD

**Issue by ZhenyaKh** [StanfordSNR/pantheon#63]
Due to this command:

```
sh_cmd = (
            'export MIN_RTT=1000000 && %s serverip=%s serverport=%s if=%s '
            'offduration=1 onduration=1000000 traffic_params=deterministic,'
            'num_cycles=1' % (send_src, args.ip, args.port, rat_file))
```

where the problematic **send_src** is defined as:

```
    cc_repo = path.join(context.third_party_dir, 'genericCC')
    recv_src = path.join(cc_repo, 'receiver')
    send_src = path.join(cc_repo, 'sender')
```

**Comment by francisyyan** [comment]
Thank you for opening the issue! It's valid for a path to have spaces (and other bizarre characters), but the recommendation is to not use them, since they will not be supported by various software, including Pantheon. I will close the issue for now, but please feel free to post in our Google group if you have any other questions (after removing spaces from the path).
