### ISSUE TITLE
Broken pipe when test pantheon

### ISSUE THREAD

**Issue by wushilan** [StanfordSNR/pantheon#68]
Hello
I meet this problem when running the test.py.
How should this be solved？
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/56755502/67937313-52c39c80-fc08-11e9-80a0-f7d91d075ca9.png">
best wishes

**Comment by francisyyan** [comment]
Hello,

This can be caused by a few reasons, such as not installing Pantheon-tunnel correctly, but a general debugging strategy is to manually run the commands printed out by `test.py` in terminals. For instance, run `mm-tunnelserver` in one terminal and its output in another, which should establish a Pantheon-tunnel if the installation/setup is correct.

If you encounter other problems, please post your question to our [Google group](https://groups.google.com/forum/#!forum/pantheon-stanford). Thank you!

Best,
Francis
